### ISSUE TITLE
Sony Alpha 7 II support?

### ISSUE THREAD

**Issue by mvodep** [locana/locana#53]
Using Sony Alpha 7 II:
Firmeware (2.0?) and Smart-Remote 4.10 (Updated today). I get:

"Remote request failed" (Locana 1.4.1.0) when i start the app (app detects the WLAN from the camera). Any hints? Thanks

**Comment by kazyx** [comment]
Thank you for the report.

Could you also check with Locana Windows 10 beta v2.0.15?

**Comment by kazyx** [comment]
We can invite you as a beta tester of Windows 10 version if your phone is running Windows 10.

**Comment by mvodep** [comment]
With 1.4.2.0 everything works perfect!!!! Thanks a lot!!! Perfect work!!!

**Comment by kazyx** [comment]
No problem.
Thank you for the report again.
