### ISSUE TITLE
Bulb mode does not work on a6000

### ISSUE THREAD

**Issue by eduguedes** [locana/locana#71]
Hello. Tried to use bulb mode several times, however the app always insists in saying that the memory card should not be inserted, however if I choose another shooting mode other than bulb everything works normally.
![wp_ss_20160811_0001](https://cloud.githubusercontent.com/assets/20978946/17606623/e04417bc-5ff6-11e6-8ae1-c62bcabb1dba.png)

**Comment by naotaco** [comment]
Hi eduguedes,

Thanks for reporting!

Yes, BULB is selectable as shutter speed setting, but triggering shutter on bulb mode is not supported for 3rd party apps...　(Only way to take photo on bulb mode is using shutter button on your camera)

It's not understandable, but current API restriction. Thank you for understanding.
