### ISSUE TITLE
No Controls if in manual mode

### ISSUE THREAD

**Issue by mvodep** [locana/locana#84]
Camera: Sony Alpha 7 II (1.20)
Smart Remote Control: 4.10
Locana: 2.2.0.0

If i use "A" mode on camera - everything works fine: I see a symbol for chaning "A", "EV", "ISO" in Locana.
If i use "M" mode, i can only see "EV" - but I'm not able to change aperture or shutter speed (symbols are missing)

Expected: Also Symbols for ISO, shutter speed and aperture are visible

**Comment by naotaco** [comment]
Hi,

Thanks for reporting it. But it's not repro here; could you share us some more things?

- What device are you using?(PC or phone?)
- Could you share us Locana's screen shot?
- It it's possible, please give us a photo of your camera's screen.

Thanks,

**Comment by naotaco** [comment]
Hi,

I'll close this for now.

If it still happens on the latest version, please reopen and share us detail.

Thanks,
