### ISSUE TITLE
Not connecting to phone after Creators update. :(

### ISSUE THREAD

**Issue by Viruslav** [locana/locana#88]
Locana doesn't show the Network Storage button anymore on my Lumia 650 phone. I cannot connect in both Remote and Photo Gallery modes. Perhaps this is after Creators update. It does work on PC though.
My camera is Sony Nex-6. It used to work very well before.

**Comment by kazyx** [comment]
Can you try re-install Locana?
Something might broken by OS upgrade.

**Comment by Viruslav** [comment]
I did it. I tried restarting the phone, resetting the app, removing and installing the app but unfortunately nothing worked. :(

**Comment by Viruslav** [comment]
I'm sorry I bothered you. I removed the saved wi-fi connection to the camera and set it up again. And after restarting Locana it found the phone! I was so afraid the app didn't support Creators update. Now I'm happy again! :)

**Comment by kazyx** [comment]
Umm... Can you get debug logs and send it to us?

1. Connect Wi-Fi to camera.
1. Open side menu in Locana and select "About Locana"
1. "Advanced settings" -> Enable "Debug logging mode" 
1. Open side menu in Locana and select "Remote"
1. Wait for about 1 minutes.
1. Open side menu in Locana and select "About Locana"
1. "Advanced settings" -> Disable "Debug logging mode" and allow to attach to e-mail
1. Send it to us.

**Comment by Viruslav** [comment]
Debug log is not needed anymore, is it? Thanks!

**Comment by kazyx** [comment]
Oh, that's great. Enjoy our app!

**Comment by Viruslav** [comment]
I really do! Thank you!
